In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import requests
import json

In [ ]:
# Load in site water level data dictionary
with open('/capstone/aridgw/data/site_data/site_coords.json', 'r') as f:
    site_coords = {k: tuple(v) for k, v in json.load(f).items()}

# Load in clean water level data csv that will be merged to
clean_site_data = "/capstone/aridgw/data/site_data/clean_site_waterdata.csv"
df_sites = pd.read_csv(clean_site_data)

# Load in clean water level data csv that will be merged to
# clean_et_monthly_data = "/capstone/aridgw/data/site_data/openet_et_monthly_clean.csv"
# df_monthly = pd.read_csv(clean_et_monthly_data)

# df_monthly = df_monthly[~((df_monthly["year"] == 2019) & (df_monthly["version"] == 2.1))]

In [ ]:

# Use API to access OpenET Data
header = {"Authorization": "31WmFjhG0zzzyqT7LyXfuTS9sHopnzU90kxnLRFSPAuwE8w4N7kg6zuPeBRs"}

# Set sites query parameter to site coordinates dictionary
sites = site_coords

# Select boundary box size
size_km = 1

# Extract data sections less than 10 years as required by the API
date_ranges = [
    ("2000-01-01", "2009-12-31", 2.0), 
    ("2010-01-01", "2019-12-31", 2.0),
    ("2020-01-01", "2025-12-31", 2.1), # Use version 2.1 for newer versions which may not have accurate data in older versions
]

dfs = [] # Create empty dataframe

# Create function to generate boundary box given coordinates and boundary box size
def make_square_geometry(lat, lon, size_km=1):
    half = size_km / 2
    lat_offset = half / 111.0
    lon_offset = half / (111.0 * np.cos(np.radians(lat)))
    return [
        lon - lon_offset, lat + lat_offset,
        lon - lon_offset, lat - lat_offset,
        lon + lon_offset, lat - lat_offset,
        lon + lon_offset, lat + lat_offset
    ]

# Use API to extract ET data 
for name, (lat, lon) in sites.items():
    print(f"Querying {name}...")
    
    for start_date, end_date, version in date_ranges:

        polygon_args = { # Define query paramters
            "date_range": [start_date, end_date],
            "interval": "monthly",
            "geometry": make_square_geometry(lat, lon, size_km),
            "model": "Ensemble",
            "reducer": "mean",
            "variable": "ET",
            "reference_et": "gridMET",
            "units": "mm",
            "file_format": "JSON",
            "version": version
        }

        resp = requests.post( # Request polygon API for this extraction
            headers=header,
            json=polygon_args,
            url="https://openet-api.org/raster/timeseries/polygon"
        )

        print(f"  {name} {start_date}–{end_date} — Status: {resp.status_code}") # Report status of data to console

        if resp.status_code != 200: # Return error if unable to extract data
            print(f"  ERROR: {resp.json()}")
            continue

        data = resp.json()
        df = pd.DataFrame(data)

        # Add columns to dataframe to specify site specific information
        df["site"] = name
        df["latitude"] = lat
        df["longitude"] = lon
        df["radius_km"] = size_km
        df["version"] = version
        dfs.append(df)

df_monthly = pd.concat(dfs, ignore_index=True) # Add new data as new observations in dataframe
print(df_monthly.head())

Querying KSGS.371852100505801...
  KSGS.371852100505801 2000-01-01–2009-12-31 — Status: 200
  KSGS.371852100505801 2010-01-01–2019-12-31 — Status: 200
  KSGS.371852100505801 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.372043101363101...
  KSGS.372043101363101 2000-01-01–2009-12-31 — Status: 200
  KSGS.372043101363101 2010-01-01–2019-12-31 — Status: 200
  KSGS.372043101363101 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.372539100142504...
  KSGS.372539100142504 2000-01-01–2009-12-31 — Status: 200
  KSGS.372539100142504 2010-01-01–2019-12-31 — Status: 200
  KSGS.372539100142504 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.373331098033301...
  KSGS.373331098033301 2000-01-01–2009-12-31 — Status: 200
  KSGS.373331098033301 2010-01-01–2019-12-31 — Status: 200
  KSGS.373331098033301 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.373607100565301...
  KSGS.373607100565301 2000-01-01–2009-12-31 — Status: 200
  KSGS.373607100565301 2010-01-01–2019-12-31 — Status: 200
  KSGS.373607100565301 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.374111099070401...
  KSGS.374111099070401 2000-01-01–2009-12-31 — Status: 200
  KSGS.374111099070401 2010-01-01–2019-12-31 — Status: 200
  KSGS.374111099070401 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.374125100344101...
  KSGS.374125100344101 2000-01-01–2009-12-31 — Status: 200
  KSGS.374125100344101 2010-01-01–2019-12-31 — Status: 200
  KSGS.374125100344101 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.374747100552101...
  KSGS.374747100552101 2000-01-01–2009-12-31 — Status: 200
  KSGS.374747100552101 2010-01-01–2019-12-31 — Status: 200
  KSGS.374747100552101 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.375145100485701...
  KSGS.375145100485701 2000-01-01–2009-12-31 — Status: 200
  KSGS.375145100485701 2010-01-01–2019-12-31 — Status: 200
  KSGS.375145100485701 2019-01-01–2025-12-31 — Status: 200
Querying KSGS.375454101075401...
  KSGS.375454101075401 2000-01-01–2009-12-31 — Status: 200
  KSGS.375454101075401 2010-01-01–2019-12-31 — Status: 200
  KSGS.375454101075401 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.0753701...
  TWDB.0753701 2000-01-01–2009-12-31 — Status: 200
  TWDB.0753701 2010-01-01–2019-12-31 — Status: 200
  TWDB.0753701 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.1005225...
  TWDB.1005225 2000-01-01–2009-12-31 — Status: 200
  TWDB.1005225 2010-01-01–2019-12-31 — Status: 200
  TWDB.1005225 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.1038101...
  TWDB.1038101 2000-01-01–2009-12-31 — Status: 200
  TWDB.1038101 2010-01-01–2019-12-31 — Status: 200
  TWDB.1038101 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.1039702...
  TWDB.1039702 2000-01-01–2009-12-31 — Status: 200
  TWDB.1039702 2010-01-01–2019-12-31 — Status: 200
  TWDB.1039702 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.1157901...
  TWDB.1157901 2000-01-01–2009-12-31 — Status: 200
  TWDB.1157901 2010-01-01–2019-12-31 — Status: 200
  TWDB.1157901 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.2409103...
  TWDB.2409103 2000-01-01–2009-12-31 — Status: 200
  TWDB.2409103 2010-01-01–2019-12-31 — Status: 200
  TWDB.2409103 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.2409801...
  TWDB.2409801 2000-01-01–2009-12-31 — Status: 200
  TWDB.2409801 2010-01-01–2019-12-31 — Status: 200
  TWDB.2409801 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.2423701...
  TWDB.2423701 2000-01-01–2009-12-31 — Status: 200
  TWDB.2423701 2010-01-01–2019-12-31 — Status: 200
  TWDB.2423701 2019-01-01–2025-12-31 — Status: 200
Querying TWDB.2453902...
  TWDB.2453902 2000-01-01–2009-12-31 — Status: 200
  TWDB.2453902 2010-01-01–2019-12-31 — Status: 200
  TWDB.2453902 2019-01-01–2025-12-31 — Status: 200
Querying UNLCSD.423037099353801...
  UNLCSD.423037099353801 2000-01-01–2009-12-31 — Status: 200
  UNLCSD.423037099353801 2010-01-01–2019-12-31 — Status: 200
  UNLCSD.423037099353801 2019-01-01–2025-12-31 — Status: 200
Querying USGS.252814080244101...
  USGS.252814080244101 2000-01-01–2009-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.252814080244101 2010-01-01–2019-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.252814080244101 2019-01-01–2025-12-31 — Status: 200
Querying USGS.252928080332401...
  USGS.252928080332401 2000-01-01–2009-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.252928080332401 2010-01-01–2019-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.252928080332401 2019-01-01–2025-12-31 — Status: 200
Querying USGS.253632080321101...
  USGS.253632080321101 2000-01-01–2009-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.253632080321101 2010-01-01–2019-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.253632080321101 2019-01-01–2025-12-31 — Status: 200
Querying USGS.272655080401601...
  USGS.272655080401601 2000-01-01–2009-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.272655080401601 2010-01-01–2019-12-31 — Status: 404
  ERROR: {'detail': 'There are 0 rasters which meet the request criteria.'}
  USGS.272655080401601 2019-01-01–2025-12-31 — Status: 200
Querying USGS.335258091152301...
  USGS.335258091152301 2000-01-01–2009-12-31 — Status: 200
  USGS.335258091152301 2010-01-01–2019-12-31 — Status: 200
  USGS.335258091152301 2019-01-01–2025-12-31 — Status: 200
Querying USGS.340440091231201...
  USGS.340440091231201 2000-01-01–2009-12-31 — Status: 200
  USGS.340440091231201 2010-01-01–2019-12-31 — Status: 200
  USGS.340440091231201 2019-01-01–2025-12-31 — Status: 200
Querying USGS.342649091251916...
  USGS.342649091251916 2000-01-01–2009-12-31 — Status: 200
  USGS.342649091251916 2010-01-01–2019-12-31 — Status: 200
  USGS.342649091251916 2019-01-01–2025-12-31 — Status: 200
Querying USGS.345519091505401...
  USGS.345519091505401 2000-01-01–2009-12-31 — Status: 200
  USGS.345519091505401 2010-01-01–2019-12-31 — Status: 200
  USGS.345519091505401 2019-01-01–2025-12-31 — Status: 200
Querying USGS.350029090265801...
  USGS.350029090265801 2000-01-01–2009-12-31 — Status: 200
  USGS.350029090265801 2010-01-01–2019-12-31 — Status: 200
  USGS.350029090265801 2019-01-01–2025-12-31 — Status: 200
Querying USGS.373644113411501...
  USGS.373644113411501 2000-01-01–2009-12-31 — Status: 200
  USGS.373644113411501 2010-01-01–2019-12-31 — Status: 200
  USGS.373644113411501 2019-01-01–2025-12-31 — Status: 200
Querying USGS.381901113014102...
  USGS.381901113014102 2000-01-01–2009-12-31 — Status: 200
  USGS.381901113014102 2010-01-01–2019-12-31 — Status: 200
  USGS.381901113014102 2019-01-01–2025-12-31 — Status: 200
Querying USGS.383921112175901...
  USGS.383921112175901 2000-01-01–2009-12-31 — Status: 200
  USGS.383921112175901 2010-01-01–2019-12-31 — Status: 200
  USGS.383921112175901 2019-01-01–2025-12-31 — Status: 200
Querying USGS.390819111530701...
  USGS.390819111530701 2000-01-01–2009-12-31 — Status: 200
  USGS.390819111530701 2010-01-01–2019-12-31 — Status: 200
  USGS.390819111530701 2019-01-01–2025-12-31 — Status: 200
Querying USGS.392601112412201...
  USGS.392601112412201 2000-01-01–2009-12-31 — Status: 200
  USGS.392601112412201 2010-01-01–2019-12-31 — Status: 200
  USGS.392601112412201 2019-01-01–2025-12-31 — Status: 200
Querying USGS.400932101404101...
  USGS.400932101404101 2000-01-01–2009-12-31 — Status: 200
  USGS.400932101404101 2010-01-01–2019-12-31 — Status: 200
  USGS.400932101404101 2019-01-01–2025-12-31 — Status: 200
Querying USGS.402103099402900...
  USGS.402103099402900 2000-01-01–2009-12-31 — Status: 200
  USGS.402103099402900 2010-01-01–2019-12-31 — Status: 200
  USGS.402103099402900 2019-01-01–2025-12-31 — Status: 200
Querying USGS.402408099584800...
  USGS.402408099584800 2000-01-01–2009-12-31 — Status: 200
  USGS.402408099584800 2010-01-01–2019-12-31 — Status: 200
  USGS.402408099584800 2019-01-01–2025-12-31 — Status: 200
Querying USGS.403235101395501...
  USGS.403235101395501 2000-01-01–2009-12-31 — Status: 200
  USGS.403235101395501 2010-01-01–2019-12-31 — Status: 200
  USGS.403235101395501 2019-01-01–2025-12-31 — Status: 200
Querying USGS.403949098182201...
  USGS.403949098182201 2000-01-01–2009-12-31 — Status: 200
  USGS.403949098182201 2010-01-01–2019-12-31 — Status: 200
  USGS.403949098182201 2019-01-01–2025-12-31 — Status: 200
Querying USGS.412603099492001...
  USGS.412603099492001 2000-01-01–2009-12-31 — Status: 200
  USGS.412603099492001 2010-01-01–2019-12-31 — Status: 200
  USGS.412603099492001 2019-01-01–2025-12-31 — Status: 200
Querying USGS.415754112551301...
  USGS.415754112551301 2000-01-01–2009-12-31 — Status: 200
  USGS.415754112551301 2010-01-01–2019-12-31 — Status: 200
  USGS.415754112551301 2019-01-01–2025-12-31 — Status: 200
Querying USGS.433218112191601...
  USGS.433218112191601 2000-01-01–2009-12-31 — Status: 200
  USGS.433218112191601 2010-01-01–2019-12-31 — Status: 200
  USGS.433218112191601 2019-01-01–2025-12-31 — Status: 200
Querying USGS.434102112180701...
  USGS.434102112180701 2000-01-01–2009-12-31 — Status: 200
  USGS.434102112180701 2010-01-01–2019-12-31 — Status: 200
  USGS.434102112180701 2019-01-01–2025-12-31 — Status: 200
Querying USGS.434657112282201...
  USGS.434657112282201 2000-01-01–2009-12-31 — Status: 200
  USGS.434657112282201 2010-01-01–2019-12-31 — Status: 200
  USGS.434657112282201 2019-01-01–2025-12-31 — Status: 200
Querying USSCS.352158090232301...
  USSCS.352158090232301 2000-01-01–2009-12-31 — Status: 200
  USSCS.352158090232301 2010-01-01–2019-12-31 — Status: 200
  USSCS.352158090232301 2019-01-01–2025-12-31 — Status: 200
Querying USSCS.355018090512401...
  USSCS.355018090512401 2000-01-01–2009-12-31 — Status: 200
  USSCS.355018090512401 2010-01-01–2019-12-31 — Status: 200
  USSCS.355018090512401 2019-01-01–2025-12-31 — Status: 200
Querying willcox...
  willcox 2000-01-01–2009-12-31 — Status: 200
  willcox 2010-01-01–2019-12-31 — Status: 200
  willcox 2019-01-01–2025-12-31 — Status: 200
Querying cuyama...
  cuyama 2000-01-01–2009-12-31 — Status: 200
  cuyama 2010-01-01–2019-12-31 — Status: 200
  cuyama 2019-01-01–2025-12-31 — Status: 200
Querying amargosa...
  amargosa 2000-01-01–2009-12-31 — Status: 200
  amargosa 2010-01-01–2019-12-31 — Status: 200
  amargosa 2019-01-01–2025-12-31 — Status: 200
Querying san_simon_valley...
  san_simon_valley 2000-01-01–2009-12-31 — Status: 200
  san_simon_valley 2010-01-01–2019-12-31 — Status: 200
  san_simon_valley 2019-01-01–2025-12-31 — Status: 200
Querying butler_valley...
  butler_valley 2000-01-01–2009-12-31 — Status: 200
  butler_valley 2010-01-01–2019-12-31 — Status: 200
  butler_valley 2019-01-01–2025-12-31 — Status: 200
Querying mcmullen_valley...
  mcmullen_valley 2000-01-01–2009-12-31 — Status: 200
  mcmullen_valley 2010-01-01–2019-12-31 — Status: 200
  mcmullen_valley 2019-01-01–2025-12-31 — Status: 200
Querying hualapai_valley...
  hualapai_valley 2000-01-01–2009-12-31 — Status: 200
  hualapai_valley 2010-01-01–2019-12-31 — Status: 200
  hualapai_valley 2019-01-01–2025-12-31 — Status: 200
Querying southern_willcox...
  southern_willcox 2000-01-01–2009-12-31 — Status: 200
  southern_willcox 2010-01-01–2019-12-31 — Status: 200
  southern_willcox 2019-01-01–2025-12-31 — Status: 200
         time       et                  site  latitude  longitude  radius_km  \
0  2000-01-01   12.573  KSGS.371852100505801  37.31502  -100.8505          1
1  2000-02-01   27.326  KSGS.371852100505801  37.31502  -100.8505          1
2  2000-03-01   40.734  KSGS.371852100505801  37.31502  -100.8505          1
3  2000-04-01   55.314  KSGS.371852100505801  37.31502  -100.8505          1
4  2000-05-01  104.492  KSGS.371852100505801  37.31502  -100.8505          1

   version
0      2.0
1      2.0
2      2.0
3      2.0
4      2.0

In [17]:
# Convert time column to datetime, extract year
df_monthly["time"] = pd.to_datetime(df_monthly["time"])
df_monthly["year"] = df_monthly["time"].dt.year
df_monthly

,time,et,site,latitude,longitude,radius_km,version,year
0,2000-01-01,12.573,KSGS.371852100505801,37.31502,-100.8505,1,2.0,2000
1,2000-02-01,27.326,KSGS.371852100505801,37.31502,-100.8505,1,2.0,2000
2,2000-03-01,40.734,KSGS.371852100505801,37.31502,-100.8505,1,2.0,2000
3,2000-04-01,55.314,KSGS.371852100505801,37.31502,-100.8505,1,2.0,2000
4,2000-05-01,104.492,KSGS.371852100505801,37.31502,-100.8505,1,2.0,2000
...,...,...,...,...,...,...,...,...
16531,2025-08-01,70.545,southern_willcox,31.36597,-109.6630,1,2.1,2025
16532,2025-09-01,44.656,southern_willcox,31.36597,-109.6630,1,2.1,2025
16533,2025-10-01,47.854,southern_willcox,31.36597,-109.6630,1,2.1,2025
16534,2025-11-01,27.207,southern_willcox,31.36597,-109.6630,1,2.1,2025
16535,2025-12-01,20.378,southern_willcox,31.36597,-109.6630,1,2.1,2025

In [35]:
# Convert monthly ET data into csv
df_monthly.to_csv("openet_data_monthly.csv", index=False)

In [36]:
# Check number of monthly et observations per site 
df_monthly.groupby(["site"]).size().reset_index(name="n")

                      site    n
0     KSGS.371852100505801  312
1     KSGS.372043101363101  312
2     KSGS.372539100142504  312
3     KSGS.373331098033301  312
4     KSGS.373607100565301  312
5     KSGS.374111099070401  312
6     KSGS.374125100344101  312
7     KSGS.374747100552101  312
8     KSGS.375145100485701  312
9     KSGS.375454101075401  312
10            TWDB.0753701  312
11            TWDB.1005225  312
12            TWDB.1038101  312
13            TWDB.1039702  312
14            TWDB.1157901  312
15            TWDB.2409103  312
16            TWDB.2409801  312
17            TWDB.2423701  312
18            TWDB.2453902  312
19  UNLCSD.423037099353801  312
20    USGS.252814080244101   72
21    USGS.252928080332401   72
22    USGS.253632080321101   72
23    USGS.272655080401601   72
24    USGS.335258091152301  312
25    USGS.340440091231201  312
26    USGS.342649091251916  312
27    USGS.345519091505401  312
28    USGS.350029090265801  312
29    USGS.373644113411501  312
30    USGS.381901113014102  312
31    USGS.383921112175901  312
32    USGS.390819111530701  312
33    USGS.392601112412201  312
34    USGS.400932101404101  312
35    USGS.402103099402900  312
36    USGS.402408099584800  312
37    USGS.403235101395501  312
38    USGS.403949098182201  312
39    USGS.412603099492001  312
40    USGS.415754112551301  312
41    USGS.433218112191601  312
42    USGS.434102112180701  312
43    USGS.434657112282201  312
44   USSCS.352158090232301  312
45   USSCS.355018090512401  312
46                amargosa  312
47           butler_valley  312
48                  cuyama  312
49         hualapai_valley  312
50         mcmullen_valley  312
51        san_simon_valley  312
52        southern_willcox  312
53                 willcox  312

In [37]:
# Calculate annual sum of monthly ET data 
df_annual = df_monthly.groupby(['site', 'year', 'version', 'radius_km'])['et'].sum().reset_index()

In [38]:
# Convert annual ET data into csv
df_annual.to_csv("openet_data_annual.csv", index=False)

In [39]:
# Check number of annual et observations per site 
df_annual.groupby(["site"]).size().reset_index(name="n")

                      site   n
0     KSGS.371852100505801  26
1     KSGS.372043101363101  26
2     KSGS.372539100142504  26
3     KSGS.373331098033301  26
4     KSGS.373607100565301  26
5     KSGS.374111099070401  26
6     KSGS.374125100344101  26
7     KSGS.374747100552101  26
8     KSGS.375145100485701  26
9     KSGS.375454101075401  26
10            TWDB.0753701  26
11            TWDB.1005225  26
12            TWDB.1038101  26
13            TWDB.1039702  26
14            TWDB.1157901  26
15            TWDB.2409103  26
16            TWDB.2409801  26
17            TWDB.2423701  26
18            TWDB.2453902  26
19  UNLCSD.423037099353801  26
20    USGS.252814080244101   6
21    USGS.252928080332401   6
22    USGS.253632080321101   6
23    USGS.272655080401601   6
24    USGS.335258091152301  26
25    USGS.340440091231201  26
26    USGS.342649091251916  26
27    USGS.345519091505401  26
28    USGS.350029090265801  26
29    USGS.373644113411501  26
30    USGS.381901113014102  26
31    USGS.383921112175901  26
32    USGS.390819111530701  26
33    USGS.392601112412201  26
34    USGS.400932101404101  26
35    USGS.402103099402900  26
36    USGS.402408099584800  26
37    USGS.403235101395501  26
38    USGS.403949098182201  26
39    USGS.412603099492001  26
40    USGS.415754112551301  26
41    USGS.433218112191601  26
42    USGS.434102112180701  26
43    USGS.434657112282201  26
44   USSCS.352158090232301  26
45   USSCS.355018090512401  26
46                amargosa  26
47           butler_valley  26
48                  cuyama  26
49         hualapai_valley  26
50         mcmullen_valley  26
51        san_simon_valley  26
52        southern_willcox  26
53                 willcox  26

In [40]:
# Merge ET data to water level data 
df_merged_et = pd.merge(
    df_sites,
    df_annual,
    left_on=['site_id', 'year_value'],
    right_on=['site', 'year'],
    how='outer' # Keep all rows for both data frames
)

In [41]:
# Check number of observations per site in merged df
df_merged_et.groupby(["site_id"]).size().reset_index(name="n")

                   site_id   n
0     KSGS.371852100505801  21
1     KSGS.372043101363101  21
2     KSGS.372539100142504  21
3     KSGS.373331098033301  21
4     KSGS.373607100565301  21
5     KSGS.374111099070401  21
6     KSGS.374125100344101  21
7     KSGS.374747100552101  21
8     KSGS.375145100485701  21
9     KSGS.375454101075401  21
10            TWDB.0753701  21
11            TWDB.1005225  21
12            TWDB.1038101  21
13            TWDB.1039702  21
14            TWDB.1157901  21
15            TWDB.2409103  21
16            TWDB.2409801  21
17            TWDB.2423701  21
18            TWDB.2453902  21
19  UNLCSD.423037099353801  21
20    USGS.252814080244101  21
21    USGS.252928080332401  21
22    USGS.253632080321101  21
23    USGS.272655080401601  21
24    USGS.335258091152301  21
25    USGS.340440091231201  21
26    USGS.342649091251916  21
27    USGS.345519091505401  21
28    USGS.350029090265801  21
29    USGS.373644113411501  21
30    USGS.381901113014102  21
31    USGS.383921112175901  21
32    USGS.390819111530701  21
33    USGS.392601112412201  21
34    USGS.400932101404101  21
35    USGS.402103099402900  21
36    USGS.402408099584800  21
37    USGS.403235101395501  21
38    USGS.403949098182201  21
39    USGS.412603099492001  21
40    USGS.415754112551301  21
41    USGS.433218112191601  21
42    USGS.434102112180701  21
43    USGS.434657112282201  21
44   USSCS.352158090232301  21
45   USSCS.355018090512401  21
46                amargosa  23
47           butler_valley  16
48                  cuyama  19
49         hualapai_valley   9
50         mcmullen_valley  24
51        san_simon_valley  12
52        southern_willcox  10
53                 willcox  16

In [ ]:
# Turn merged df into csv
df_merged_et.to_csv("merged_openet_data.csv", index=False)